<?php
define('EDITORS_CHOISE', 'Избрани от редактора');
define('HOME', 'Начало');
define('CATEGORIES', 'Категории');
define('LANDMARKS', 'Забележителности');
define('NATURAL', 'Природни');
define('HISTORICAL', 'Исторически');
define('ARCHITECTURAL', 'Архитектурни');
define('GALLERY', 'Галерия');
define('ABOUT_US', 'За нас');
define('CONTACTS', 'Контакти');
define('COUNTRY', 'България');
define('PHONE', 'Телефон');
define('MAIL', 'Имейл');
define('INSTAGRAM', 'Последвайте ни в Instagram');
define('BRIDGE', 'Дяволският мост');
define('EAGLE_ROCKS', 'Тракийско светилище Орлови скали');
define('Kardzhali_Dam', 'Язовир, Кърджали');
define('MELNIK', 'град Мелник');
define('FOREST', 'Вкаменената гора');
define('RILA', 'Рилските езера');
define('MUSEUM', 'Регионален исторически музей, Кърджали');
define('PERPERIKON', 'Археологически комплекс Перперикон');
define('STATUE', 'Паметник на Орфей');
define('SWAN_VILLAGE', 'Езерата край село Лебед');
define('STONE', 'Каммените гъби');
define('USTRA', 'Средновековна крепост Устра');
define('UTROBA', 'Пещера Утробата');
define('READ_MORE', 'Научи повече');
?>
